<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="360LP040" name="com.edureka.scripts.VerifyUserCannotLoggedInWithIncorrectEmailAndCorrectPassword" tests="2" failures="1" timestamp="5 Jul 2016 14:59:18 GMT" time="19.728" errors="1">
  <testcase name="test_014serCannotLoggedInWithoutPassword" time="0.000" classname="com.edureka.scripts.VerifyUserCannotLoggedInWithIncorrectEmailAndCorrectPassword">
    <error type="java.lang.Throwable" message="Method VerifyUserCannotLoggedInWithIncorrectEmailAndCorrectPassword.test_014serCannotLoggedInWithoutPassword()[pri:0, instance:com.edureka.scripts.VerifyUserCannotLoggedInWithIncorrectEmailAndCorrectPassword@6574b225] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method VerifyUserCannotLoggedInWithIncorrectEmailAndCorrectPassword.test_014serCannotLoggedInWithoutPassword()[pri:0, instance:com.edureka.scripts.VerifyUserCannotLoggedInWithIncorrectEmailAndCorrectPassword@6574b225] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1040)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
    </error>
  </testcase> <!-- test_014serCannotLoggedInWithoutPassword -->
  <testcase name="test_013UserCannotLoggedInWithIncorrectEmailAndCorrectPassword" time="19.728" classname="com.edureka.scripts.VerifyUserCannotLoggedInWithIncorrectEmailAndCorrectPassword">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.edureka.pages.SignInModalPage.verifyErrorForLogIn(SignInModalPage.java:329)
	at com.edureka.scripts.VerifyUserCannotLoggedInWithIncorrectEmailAndCorrectPassword.test_013UserCannotLoggedInWithIncorrectEmailAndCorrectPassword(VerifyUserCannotLoggedInWithIncorrectEmailAndCorrectPassword.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
    </failure>
  </testcase> <!-- test_013UserCannotLoggedInWithIncorrectEmailAndCorrectPassword -->
</testsuite> <!-- com.edureka.scripts.VerifyUserCannotLoggedInWithIncorrectEmailAndCorrectPassword -->
