<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="360LP048" name="com.edureka.leadProcess.VerifySignupFromEnrollOnAnyCourse" tests="3" failures="0" timestamp="16 Sep 2016 12:11:50 GMT" time="486.697" errors="2">
  <testcase name="test_023EnrollOnAnyCourseLandingPage" time="0.000" classname="com.edureka.leadProcess.VerifySignupFromEnrollOnAnyCourse">
    <error type="java.lang.Throwable" message="Method VerifySignupFromEnrollOnAnyCourse.test_023EnrollOnAnyCourseLandingPage()[pri:0, instance:com.edureka.leadProcess.VerifySignupFromEnrollOnAnyCourse@e45f292] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method VerifySignupFromEnrollOnAnyCourse.test_023EnrollOnAnyCourseLandingPage()[pri:0, instance:com.edureka.leadProcess.VerifySignupFromEnrollOnAnyCourse@e45f292] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1040)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
    </error>
  </testcase> <!-- test_023EnrollOnAnyCourseLandingPage -->
  <testcase name="test_014SignInEnrollOnAnyCourse" time="200.084" classname="com.edureka.leadProcess.VerifySignupFromEnrollOnAnyCourse">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at java.lang.String.contains(String.java:2133)
	at com.edureka.pages.DatabaseVerifications.dataVerificationInUser_Events_Table(DatabaseVerifications.java:169)
	at com.edureka.pages.OrderSummaryPage.dataVerificationInUser_EventTable(OrderSummaryPage.java:222)
	at com.edureka.leadProcess.VerifySignupFromEnrollOnAnyCourse.test_014SignInEnrollOnAnyCourse(VerifySignupFromEnrollOnAnyCourse.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
    </error>
  </testcase> <!-- test_014SignInEnrollOnAnyCourse -->
  <testcase name="test_005VerifySignupFromEnroll" time="286.613" classname="com.edureka.leadProcess.VerifySignupFromEnrollOnAnyCourse"/>
</testsuite> <!-- com.edureka.leadProcess.VerifySignupFromEnrollOnAnyCourse -->
