<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="360pc011" name="com.edureka.paymentProcess.MakePaymentWhenB1S2OfferAndCourseOtherThanIwillChooseLater" tests="3" failures="1" timestamp="2 Feb 2017 13:03:36 GMT" time="120.246" errors="2">
  <testcase name="test_021MakePaymentWhenB1S2OfferAndCourseOtherThanIwillChooseLater_RP" time="0.000" classname="com.edureka.paymentProcess.MakePaymentWhenB1S2OfferAndCourseOtherThanIwillChooseLater">
    <error type="java.lang.Throwable" message="Method MakePaymentWhenB1S2OfferAndCourseOtherThanIwillChooseLater.test_021MakePaymentWhenB1S2OfferAndCourseOtherThanIwillChooseLater_RP()[pri:0, instance:com.edureka.paymentProcess.MakePaymentWhenB1S2OfferAndCourseOtherThanIwillChooseLater@40077a80] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method MakePaymentWhenB1S2OfferAndCourseOtherThanIwillChooseLater.test_021MakePaymentWhenB1S2OfferAndCourseOtherThanIwillChooseLater_RP()[pri:0, instance:com.edureka.paymentProcess.MakePaymentWhenB1S2OfferAndCourseOtherThanIwillChooseLater@40077a80] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1040)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </error>
  </testcase> <!-- test_021MakePaymentWhenB1S2OfferAndCourseOtherThanIwillChooseLater_RP -->
  <testcase name="test_021MakePaymentWhenB1S2OfferAndCourseOtherThanIwillChooseLater_Paypal" time="0.000" classname="com.edureka.paymentProcess.MakePaymentWhenB1S2OfferAndCourseOtherThanIwillChooseLater">
    <error type="java.lang.Throwable" message="Method MakePaymentWhenB1S2OfferAndCourseOtherThanIwillChooseLater.test_021MakePaymentWhenB1S2OfferAndCourseOtherThanIwillChooseLater_Paypal()[pri:0, instance:com.edureka.paymentProcess.MakePaymentWhenB1S2OfferAndCourseOtherThanIwillChooseLater@40077a80] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method MakePaymentWhenB1S2OfferAndCourseOtherThanIwillChooseLater.test_021MakePaymentWhenB1S2OfferAndCourseOtherThanIwillChooseLater_Paypal()[pri:0, instance:com.edureka.paymentProcess.MakePaymentWhenB1S2OfferAndCourseOtherThanIwillChooseLater@40077a80] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1040)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </error>
  </testcase> <!-- test_021MakePaymentWhenB1S2OfferAndCourseOtherThanIwillChooseLater_Paypal -->
  <testcase name="test_021MakePaymentWhenB1S2OfferAndCourseOtherThanIwillChooseLater_CCAvenue" time="120.246" classname="com.edureka.paymentProcess.MakePaymentWhenB1S2OfferAndCourseOtherThanIwillChooseLater">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.edureka.pages.RazorPayPage.verifyCCAvenuePage(RazorPayPage.java:132)
	at com.edureka.paymentProcess.MakePaymentWhenB1S2OfferAndCourseOtherThanIwillChooseLater.test_021MakePaymentWhenB1S2OfferAndCourseOtherThanIwillChooseLater_CCAvenue(MakePaymentWhenB1S2OfferAndCourseOtherThanIwillChooseLater.java:640)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- test_021MakePaymentWhenB1S2OfferAndCourseOtherThanIwillChooseLater_CCAvenue -->
</testsuite> <!-- com.edureka.paymentProcess.MakePaymentWhenB1S2OfferAndCourseOtherThanIwillChooseLater -->
