<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="360pc011" name="com.edureka.paymentProcess.MakePaymentThroughPaypal" tests="2" failures="1" timestamp="2 Feb 2017 13:03:36 GMT" time="175.551" errors="1">
  <testcase name="test_022ValidateMyOrdersDetailsOnMyProfilePage" time="0.000" classname="com.edureka.paymentProcess.MakePaymentThroughPaypal">
    <error type="java.lang.Throwable" message="Method MakePaymentThroughPaypal.test_022ValidateMyOrdersDetailsOnMyProfilePage()[pri:0, instance:com.edureka.paymentProcess.MakePaymentThroughPaypal@3c8587f] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method MakePaymentThroughPaypal.test_022ValidateMyOrdersDetailsOnMyProfilePage()[pri:0, instance:com.edureka.paymentProcess.MakePaymentThroughPaypal@3c8587f] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1040)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </error>
  </testcase> <!-- test_022ValidateMyOrdersDetailsOnMyProfilePage -->
  <testcase name="test_004MakePaymentThroughPaypal" time="175.551" classname="com.edureka.paymentProcess.MakePaymentThroughPaypal">
    <failure type="java.lang.AssertionError" message="Element Locator ://input[@id=&#039;confirmButtonTop&#039;] Not found expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Element Locator ://input[@id='confirmButtonTop'] Not found expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.edureka.util.DriverHelper.clickOn(DriverHelper.java:353)
	at com.edureka.pages.PayPalPage.clickOnContinueButton(PayPalPage.java:73)
	at com.edureka.paymentProcess.MakePaymentThroughPaypal.test_004MakePaymentThroughPaypal(MakePaymentThroughPaypal.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- test_004MakePaymentThroughPaypal -->
</testsuite> <!-- com.edureka.paymentProcess.MakePaymentThroughPaypal -->
